### ISSUE TITLE
This plugin doesn't seem to work with the `offline` plugin from MkDocs material

### ISSUE THREAD

**Issue by ilyagr** [mondeja/mkdocs-include-markdown-plugin#195] opened 2024-02-07 22:19 UTC
I posted a detailed report at https://github.com/squidfunk/mkdocs-material/issues/6749. I'm guessing that it's mostly the `offline` plugin's fault, but that's just a guess, and perhaps there's something on this side that could be changed to fix it.

Any advice or workarounds would also be appreciated. Thank you for making the plugin!

**Comment by mondeja** [comment] 2024-02-07 23:10
Thanks for the detailed report.

This happens because the configuration file inheritance of Mkdocs works by replacing all keys of parent inherited configurations. So, in this case, `plugins: ['include-markdown']` is replaced by `plugins: ['offline']`. 

See `mkdocs/utils/yaml.py`. This can be reproduced with:

```python
>>> import deepmerge
>>> mergedeep.merge({"plugins": ["include-markdown"]}, {"plugins": ["offline"]})
{'plugins': ['offline']}
```

Maybe, this can be considered as a bug or limitation of Mkdocs, but not sure if this is by design. I'm going to continue the research and open the corresponding discussion if appropiate. For now, you must consider redesigning how are you inheriting the configuration, as the current behaviour is the expected (see [Configuration Inheritance](https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance)).

**Comment by ilyagr** [comment] 2024-02-07 23:15
You are correct. Thank you so much, I really appreciate it!

I added all the plugins to `mkdocs-offline.yml` file for now, might try to do something more clever later.

Please share any bugs you open, if you are indeed planning to research this further.

**Comment by mondeja** [comment] 2024-02-07 23:17
Seems like this is already being discussed on https://github.com/mkdocs/mkdocs/issues/3216, so closing this for now.

**Closed by mondeja** 2024-02-07 23:17 UTC
Labels: question
