### ISSUE TITLE
Is there a way to include markdown from a remote url?

### ISSUE THREAD

**Issue by clubanderson** [mondeja/mkdocs-include-markdown-plugin#158] opened 2023-06-10 15:47 UTC
I would like to include an md file from a blob in a remote GitHub repo. Like https://GitHub.com/ccc/ddd/blob/main/mailbox.md

**Comment by mondeja** [comment] 2023-06-10 22:14
Duplicate of #138

**Closed by mondeja** 2023-06-10 22:14 UTC

**Comment by clubanderson** [comment] 2023-06-11 13:22
how do I compile and include my version of this plugin (for testing) into mkdocs?  I would like to try and build this functionality into a PR
